version: '3.8'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:admin@postgres:5432/deliverydb?sslmode=disable
      - REDIS_ADDR=redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: deliverydb
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
